In [0]:
name = input("Enter your name:")
print("Name is: " +name)

Enter your name:Sumit
Name is: Sumit


In [0]:
names = ["ben", "chen", "Yaqin"]

In [0]:
abc = names[-1]

In [0]:
abc

'Yaqin'

In [0]:
abc[2:]

'qin'

In [0]:
smiles="Sumit Kumar u. Yadav"


In [0]:
smiles

'Sumit Kumar u. Yadav'

In [0]:
smiles.find(".",14)


-1

In [0]:
smiles.split()

['Sumit', 'Kumar', 'u.', 'Yadav']

In [0]:
if "Br" in "Brother":
    print("contains brother")

contains brother


In [0]:
if "Br " in "Brother":
    print("contains brother")

In [0]:
email_address = input("Enter the email id: ")
user_id = email_address.find("@")
print(user_id)
print("user id is: " + email_address[:user_id])

Enter the email id: sahdvsagda@gmail.com
10
user id is: sahdvsagda


In [0]:
line = " # This is a comment line \n"

In [0]:
line.strip()

'# This is a comment line'

In [0]:
len(line.strip())

24

In [0]:
line.rstrip("\n")

' # This is a comment line '

In [0]:
len(line.rstrip())

25

In [0]:
line.lstrip()

'# This is a comment line \n'

In [0]:
len(line.lstrip())

26

In [0]:
line = " Google LLC is an American multinational technology company that specializes in Internet-related services and products. which include online advertising technologies, search engine, cloud computing, software, and hardware. "

In [0]:
print(line)
line = line.strip()
abc = line.split(".")
#print(abc)


 Google LLC is an American multinational technology company that specializes in Internet-related services and products. which include online advertising technologies, search engine, cloud computing, software, and hardware. 


In [0]:
word = (abc[0].split(" "))

In [0]:
word[0]

'Google'

In [0]:
ids = ["9pti", "2plv", "1crn"]

In [0]:
ids.append("1alm")

In [0]:
ids


['9pti', '2plv', '1crn', '1alm']

In [0]:

L = ["2anm", "9mnp"]
ids.extend(L)


In [0]:
del ids[0]

ids.sort()
print(ids)

ids.reverse()
print(ids)

ids.insert(0, "9pti")
print(ids)

['1alm', '1crn', '2anm', '2plv', '9mnp']
['9mnp', '2plv', '2anm', '1crn', '1alm']
['9pti', '9mnp', '2plv', '2anm', '1crn', '1alm']


In [0]:
yellow = (255, 255, 0)

one = (1,)

yellow[0]

yellow[1:]

yellow[0]

255

In [0]:
one = (1,)

In [0]:
print("%s lives in %s at lattitide %0.1f" % ("andrew", "Sweden", 57.5454))

andrew lives in Sweden at lattitide 57.5


In [0]:
names = ["one", "two", "three"]

In [0]:
gender = [1, 2, 3]

In [0]:
abc = zip(names, gender)

In [0]:
abc

In [0]:
for i in abc:
    print(i)

('one', 1)
('two', 2)
('three', 3)


In [0]:
atomic_number = {"H":"Hydrogen", "He":"Helium", "Li": "Lithium", "C":"Carbon", "O": "Oxygen", "N": "Nitrogen" }
atomic_number

{'C': 'Carbon',
 'H': 'Hydrogen',
 'He': 'Helium',
 'Li': 'Lithium',
 'N': 'Nitrogen',
 'O': 'Oxygen'}

In [0]:
type(atomic_number)

dict

In [0]:
atomic_number = {1:"Hydrogen", 2:"Helium", 3: "Lithium", 4:"Carbon", 5: "Oxygen", 5: "Nitrogen" }
atomic_number

{1: 'Hydrogen', 2: 'Helium', 3: 'Lithium', 4: 'Carbon', 5: 'Nitrogen'}

In [0]:
mode = "absolute"
if mode == "canonincal":
    smiles = "canonical"
    print(smiles)
elif mode == "isomeric":
    smiles = "isomeric"
    print(smiles)
elif mode == "absolute":
        smiles = "absolute"
        print(smiles)
else:
    raise TypeError("unknown Mode")

absolute


In [0]:
str1 = "Sumit yadav"

if "Sumit" in str1:
    print("name mached")
else:
    print("No match")

name mached


In [0]:
def match_fuction(text,abc):
    if text.find(str(abc))>=0:
        print("name mached")
    else:
        print("No match")

In [0]:
match_fuction(str1,"mayank")

No match


In [0]:
def print_series(a,b):
    for i in range(a,b+1):
        print(i)

In [0]:
print_series(1,10)

1
2
3
4
5
6
7
8
9
10


In [0]:
str1 = "He is a good boy"
str2 = "He is fast in coding"




In [0]:
def match_words(string1, string2):
    temp = string1.split()
    for i in temp:
        if string2.find(i)>=0:
            print("Found %s at"%i,string2.find(i))

In [0]:
match_words(str1,str2)

Fount He at 0
Fount is at 3
Fount a at 7


In [0]:
f = open("data.txt")
str3 = f.read()
print(str3)

Google LLC is an American multinational technology company that specializes in Internet-related services and products, which include online advertising technologies, search engine, cloud computing, software, and hardware.
It is considered one of the Big Four technology companies, alongside Amazon, Apple and Facebook.


In [0]:
string = "He is a good boy"
word = "He"


            


In [0]:

def match_words(string1, string2):
    temp = string1.split()
    for i in temp:
        if string2.find(i)>=0:
            print("Found %s at"%i,string2.find(i))

In [6]:
match_words(string,word)

Found He at 0


In [0]:
text = 'This is car'
word = 'is'
replace_word = 'is not'

In [11]:
def find_word(text,word):
  words = text.split(" ")
  words = words.index(word)
  print(words)
  
  
find_word(text,word)

1


In [14]:
def find_word(text,word):
  words = text.split(" ")
  print(type(words))
  words[words.index(word)] = replace_word
  print(words)
  
  
find_word(text,word)

<class 'list'>
['This', 'is not', 'car']


In [0]:
text = 'This is my car'
word = 'is'

In [21]:
def func(text, word):
  words = text.split()
  print(words.index(word))
  print(words)
  
  
  
func(text, word)

1
['This', 'is', 'my', 'car']


In [0]:
import numpy as np

In [25]:
a = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
print(a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [28]:
b = np.array([1], dtype=np.float32)
print(b.ndim, b.shape, b.dtype)

1 (1,) float32


In [30]:
np.ones((3,5),dtype=np.float32)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

here ''.'' represents float 32 type

In [32]:
np.zeros((6,2),dtype=np.int8)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int8)

In [36]:
np.arange(2000, 2006)


array([2000, 2001, 2002, 2003, 2004, 2005])

In [44]:
A = np.ones((2,3))
B = np.zeros((4,3))

np.concatenate([A,B])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
A = np.ones((2,3))
B = np.zeros((2,4))

np.concatenate([A,B], axis = 1)

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

In [50]:
A = np.array([[1,2.2,3,4.5,5],[6.6,7,6.8,9,10],[11,12,13,14,15]])
A

array([[ 1. ,  2.2,  3. ,  4.5,  5. ],
       [ 6.6,  7. ,  6.8,  9. , 10. ],
       [11. , 12. , 13. , 14. , 15. ]])

In [52]:
print(A.astype(np.uint16))
print(type(A.astype(np.uint16)))

[[ 1  2  3  4  5]
 [ 6  7  6  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>


In [64]:
a = np.ones((2,2,3))
b = np.zeros_like(a)
print(a)
print(b.shape)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(2, 2, 3)


In [60]:
b

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [68]:
np.random.random((10,3))

array([[0.95772716, 0.29832343, 0.25498432],
       [0.43607241, 0.50393744, 0.59234917],
       [0.88977518, 0.98499655, 0.27913952],
       [0.81350378, 0.85911323, 0.25671501],
       [0.21863581, 0.97071358, 0.24300219],
       [0.10493391, 0.91764426, 0.27045427],
       [0.89540892, 0.54626095, 0.24250719],
       [0.13521205, 0.39653879, 0.49266519],
       [0.53168434, 0.26454992, 0.19608325],
       [0.58392963, 0.15559456, 0.50567279]])

In [70]:
np.random.randint(10,size=(4,3))

array([[4, 6, 0],
       [3, 1, 6],
       [6, 7, 2],
       [8, 3, 0]])

In [72]:
a = np.array([1,2,3,4,5,6])
 
a= a.reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [75]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [81]:
a = np.arange(10).reshape(5,2)
a = a.T
a = a.transpose((1,0))

print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


###NPZ files can hold multiple Arrays

In [83]:
np.savez('data.npz', a = a)
data = np.load('data.npz')
a = data['a']
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
